main:
- name: Serviços
  pageRef: "#services"
  weight: 1
- name: Custos
  pageRef: "#costs"
  weight: 2
- name: Contato
  pageRef: "#contact-form"
  weight: 3
- name: Localização
  pageRef: "#location"
  weight: 4
- name: Links
  pageRef: "#links"
  weight: 5