main:
- name: Services
  pageRef: "#services"
  weight: 1
- name: Tarifs
  pageRef: "#costs"
  weight: 2
- name: Contactez-moi
  pageRef: "#contact-form"
  weight: 3
- name: Adresse
  pageRef: "#location"
  weight: 4
- name: Links
  pageRef: "#links"
  weight: 5